language: go

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

go:
  - 1.14.x
  - 1.18.x
  - tip

script:
  - go vet ./...
  - golangci-lint run
  - go test -short -timeout 1h ./...
  - go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb
